Repository open-mmlab/mmrotate, pull requests merged in 2022-04, with the labels that each got.

#183 [Algorithm] Update Stable KLD (NeurIPS'21)
  configs/_base_/datasets/hrsc.py
  configs/_base_/schedules/schedule_6x.py
  configs/kld/README.md
  configs/kld/metafile.yml
  configs/kld/r3det_kld_stable_r50_fpn_1x_dota_oc.py
  configs/kld/rotated_retinanet_hbb_kld_stable_r50_fpn_1x_dota_oc.py
  configs/kld/rotated_retinanet_hbb_kld_stable_r50_fpn_6x_hrsc_rr_oc.py
  configs/kld/rotated_retinanet_obb_kld_stable_r50_fpn_1x_dota_le90.py
  configs/kld/rotated_retinanet_obb_kld_stable_r50_fpn_6x_hrsc_rr_le90.py
  configs/rotated_retinanet/README.md
  configs/rotated_retinanet/metafile.yml
  configs/rotated_retinanet/rotated_retinanet_hbb_r50_fpn_6x_hrsc_rr_oc.py
  configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_6x_hrsc_rr_le90.py
Labels: enhancement, reimplementation, algorithm

#179 [Algorithm] Support Rotated ATSS-OBB (CVPR'20)
  README.md
  README_zh-CN.md
  configs/csl/README.md
  configs/rotated_atss/README.md
  configs/rotated_atss/metafile.yml
  configs/rotated_atss/r3det_atss_r50_fpn_1x_dota_oc.py
  configs/rotated_atss/rotated_atss_hbb_r50_fpn_1x_dota_oc.py
  configs/rotated_atss/rotated_atss_obb_r50_fpn_1x_dota_le135.py
  configs/rotated_atss/rotated_atss_obb_r50_fpn_1x_dota_le90.py
  configs/rotated_retinanet/metafile.yml
  docs/en/model_zoo.md
  docs/zh_cn/model_zoo.md
  mmrotate/core/bbox/__init__.py
  mmrotate/core/bbox/assigners/__init__.py
  mmrotate/core/bbox/assigners/atss_obb_assigner.py
  mmrotate/core/bbox/iou_calculators/__init__.py
  mmrotate/models/dense_heads/__init__.py
  mmrotate/models/dense_heads/rotated_atss_head.py
  mmrotate/models/dense_heads/rotated_retina_head.py
Labels: reimplementation, algorithm

#160 [Feature] support torchserve
  README.md
  docker/serve/Dockerfile
  docker/serve/config.properties
  docker/serve/entrypoint.sh
  docs/en/useful_tools.md
  setup.cfg
  tools/deployment/mmrotate2torchserve.py
  tools/deployment/mmrotate_handler.py
Labels: feature
